In [27]:
import numpy as np

In [28]:
mat1 = np.arange(1,10).reshape(3,3)
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
mat2 = np.arange(1,10)[::-1].reshape(3,3)
mat2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [61]:
def input_matrices():
  rows1 = int(input("Enter the number of rows: "))
  cols1 = int(input("Enter the number of columns: "))
  

  mat1 = []
  print("Enter the elements of the first matrix row by row:")
  for i in range(rows1):
    row = []
    for j in range(cols1):
      element = int(input(f"Enter element at position ({i+1},{j+1}): "))
      row.append(element)
    mat1.append(row)
    
  print('Matrix 1 : ')
  print(mat1)
  
  rows2 = int(input("Enter the number of rows: "))
  cols2 = int(input("Enter the number of columns: "))

  mat2 = []
  print("Enter the elements of the second matrix row by row:")
  for i in range(rows2):
    row = []
    for j in range(cols2):
      element = int(input(f"Enter element at position ({i+1},{j+1}): "))
      row.append(element)
    mat2.append(row)

  print('Matrix 2 : \n', mat2)
  print(mat2)
  
  
  return np.array(mat1), np.array(mat2)

In [41]:
def checkDimSum(a,b):
  print('Matrix 1 shape: ', np.shape(a))
  print('Matrix 2 shape: ',np.shape(b))
  return True if np.shape(a) == np.shape(b) else False

In [51]:
def matSum (mat1, mat2):
    print('Matrix Summation')
    if(not checkDimSum(mat1,mat2)):
        return 'Array size incompatible'
    
    mat3 = np.zeros((mat1.shape[0], mat2.shape[1]))

    for c in range(mat1.shape[0]):
        for r in range(mat2.shape[1]):
            mat3[c][r] = mat1[c][r] + mat2[c][r]
            
    return mat3

In [43]:
matSum(mat1,mat2)

Matrix 1 shape:  (3, 3)
Matrix 2 shape:  (3, 3)


array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [45]:
def checkDimMult(a,b):
  print('Matrix 1 shape: ', np.shape(a))
  print('Matrix 2 shape: ',np.shape(b))
  return True if np.shape(a)[0] == np.shape(b)[1] else False

In [50]:
def matMult (mat1, mat2):
    print('Matrix Multiplication')
    if(not checkDimMult(mat1,mat2)):
        return 'Array size incompatible'
    
    # Assuming mat1 and mat2 are already defined and have compatible dimensions
    mat3 = np.zeros((mat1.shape[0], mat2.shape[1]))

    for c in range(mat1.shape[0]):
        for r in range(mat2.shape[1]):
            sum = 0
            for k in range(mat1.shape[1]):
                sum += mat1[c][k] * mat2[k][r]
            mat3[c][r] = sum
            # print(sum)

    return mat3


In [47]:
matMult(mat1,mat2)

Matrix 1 shape:  (3, 3)
Matrix 2 shape:  (3, 3)


array([[ 30.,  24.,  18.],
       [ 84.,  69.,  54.],
       [138., 114.,  90.]])

In [48]:
mat3 = mat1@mat2
mat3[1][1] = 0
mat3 = np.array(mat3)
mat3 == matMult(mat1,mat2)
# matMult(mat1,mat2) == np.array(mat1@mat2)

Matrix 1 shape:  (3, 3)
Matrix 2 shape:  (3, 3)


array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True]])

Summation

In [62]:
mat1,mat2 = input_matrices()
matSum(mat1,mat2)

Enter the elements of the first matrix row by row:
Matrix 1 : 
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Enter the elements of the second matrix row by row:
Matrix 2 : 
 [[9, 8, 7], [6, 5, 4], [3, 2, 1]]
[[9, 8, 7], [6, 5, 4], [3, 2, 1]]
Matrix Summation
Matrix 1 shape:  (3, 3)
Matrix 2 shape:  (3, 3)


array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

Multiplication

In [63]:
mat1,mat2 = input_matrices()
matMult(mat1,mat2)

Enter the elements of the first matrix row by row:
Matrix 1 : 
[[1, 2, 3], [4, 5, 6]]
Enter the elements of the second matrix row by row:
Matrix 2 : 
 [[7, 8], [9, 10], [11, 12]]
[[7, 8], [9, 10], [11, 12]]
Matrix Multiplication
Matrix 1 shape:  (2, 3)
Matrix 2 shape:  (3, 2)


array([[ 58.,  64.],
       [139., 154.]])