### Importing the OpenCV Library

In this step, we import the **OpenCV** library using `import cv2`. OpenCV is a powerful library used for computer vision and image processing tasks. It provides functions to work with images, videos, and many other related operations.

- **`cv2`**: This is the module name used to access OpenCV functions in Python.
- Before using OpenCV, make sure it is installed in your environment by running `pip install opencv-python`.


In [3]:
import cv2 


### Reading an Image

In this step, we use the `cv2.imread()` function from OpenCV to read an image from a file. The function takes the path to the image file as an argument (in this case, `"app.jpg"`) and loads the image into a variable `img`. The image is stored as a NumPy array where each element represents the pixel values (BGR format by default).

If the image is not found, the function returns `None`.

- **Note**: Ensure that the image file `"app.jpg"` exists in the specified path or provide the correct file path.


In [4]:
img = cv2.imread("img/khaleel.jpg")


### Checking the Type of the Image Object

In this step, we use the `type()` function to check the data type of the `img` object. 

When an image is loaded using OpenCV's `cv2.imread()`, the image is represented as a **NumPy array**. This allows you to manipulate the image data easily, as each pixel is stored as a multi-dimensional array.

- **Expected Output**: If the image is loaded successfully, the output will be `<class 'numpy.ndarray'>`.
- If the image is not loaded properly (e.g., the file path is incorrect), the type will return `NoneType`.


In [4]:
type(img)

numpy.ndarray

In [5]:
img.shape

(1600, 800, 3)

In [6]:
width,height,channel =img.shape

In [7]:
print(f"The width is : {width} \nThe hight is: {height} \nThe number of channels: {channel} ")

The width is : 1600 
The hight is: 800 
The number of channels: 3 


In [5]:
cv2.imshow("image1",img)

# Wait for a key press and close the windows
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
print(img)

[[[ 49  25  59]
  [ 49  28  60]
  [ 47  33  57]
  ...
  [212 216 204]
  [210 214 202]
  [217 221 209]]

 [[ 42  19  51]
  [ 42  22  51]
  [ 42  29  51]
  ...
  [217 221 209]
  [215 219 207]
  [221 225 213]]

 [[ 38  16  44]
  [ 38  19  44]
  [ 40  28  48]
  ...
  [221 227 216]
  [219 225 214]
  [224 230 219]]

 ...

 [[210 200 166]
  [214 203 171]
  [216 206 176]
  ...
  [133 147 146]
  [142 154 154]
  [145 157 157]]

 [[212 203 166]
  [213 204 167]
  [214 203 171]
  ...
  [132 147 149]
  [144 156 160]
  [151 163 167]]

 [[218 209 171]
  [218 209 172]
  [219 209 175]
  ...
  [111 128 131]
  [124 136 142]
  [133 145 151]]]


In [14]:
# Split the image into its Blue, Green, and Red channels
B, G, R = cv2.split(img)

# Print each channel matrix
print("Red Channel Matrix: \n", R)
print("\nGreen Channel Matrix: \n", G)
print("\nBlue Channel Matrix: \n", B)


Red Channel Matrix: 
 [[ 59  60  57 ... 204 202 209]
 [ 51  51  51 ... 209 207 213]
 [ 44  44  48 ... 216 214 219]
 ...
 [166 171 176 ... 146 154 157]
 [166 167 171 ... 149 160 167]
 [171 172 175 ... 131 142 151]]

Green Channel Matrix: 
 [[ 25  28  33 ... 216 214 221]
 [ 19  22  29 ... 221 219 225]
 [ 16  19  28 ... 227 225 230]
 ...
 [200 203 206 ... 147 154 157]
 [203 204 203 ... 147 156 163]
 [209 209 209 ... 128 136 145]]

Blue Channel Matrix: 
 [[ 49  49  47 ... 212 210 217]
 [ 42  42  42 ... 217 215 221]
 [ 38  38  40 ... 221 219 224]
 ...
 [210 214 216 ... 133 142 145]
 [212 213 214 ... 132 144 151]
 [218 218 219 ... 111 124 133]]


In [18]:
# Optionally, display each channel as an image
cv2.imshow('Red Channel', R)
cv2.imshow('Green Channel', G)
cv2.imshow('Blue Channel', B)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
img2 = cv2.imread(r"C:\Users\PMLS\Pictures\Screenshots\kkokoma.png")
img2 = cv2.resize(img2, (700,500))

In [21]:
cv2.imshow("image",img2)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:
img2 = cv2.imread("img/kkokoma2.png")

In [24]:
cv2.imshow("image",img2)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
# Import the necessary libraries
# from sklearn.datasets import load_iris
import pandas as pd

# Load the Iris dataset
iris = load_iris()

# Display the dataset's description
print(iris.DESCR)


ModuleNotFoundError: No module named 'pandas'

In [81]:
# Display the dataset's description
print(iris.DESCR)

# Convert the dataset into a pandas DataFrame
# The dataset contains 'data' (features) and 'target' (labels)
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['species'] = iris.target

# Display the first 5 rows of the DataFrame
print(df.head())



.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========